---

services:
  sonarr:
    container_name: sonarr  
    # See more: https://docs.linuxserver.io/images/docker-sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: always
    network_mode: service:gluetun
    env_file: ./env/arr.env
    volumes:
      - sonarr:/config
      - media:/media
      - downloads:/downloads
    healthcheck:
      test: curl -f http://localhost:8989/ping || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
      caddy:
        condition: service_healthy
        restart: true
      bittorrent:
        condition: service_healthy
        restart: true
      

  radarr:
    container_name: radarr
    # See more: https://docs.linuxserver.io/images/docker-radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: always
    network_mode: service:gluetun
    env_file: ./env/arr.env
    volumes:
      - radarr:/config
      - media:/media
      - downloads:/downloads
    healthcheck:
      test: curl -f http://localhost:7878/ping || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
      caddy:
        condition: service_healthy
        restart: true
      bittorrent:
        condition: service_healthy
        restart: true

  prowlarr:
    container_name: prowlarr
    # See more: https://docs.linuxserver.io/images/docker-prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: always
    network_mode: service:gluetun
    env_file: ./env/arr.env
    volumes: 
      - prowlarr:/config
      - media:/media
      - downloads:/downloads
    healthcheck:
      test: curl -f http://localhost:9696/ping || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
      caddy:
        condition: service_healthy
        restart: true
      bittorrent:
        condition: service_healthy
        restart: true
      sonarr:
        condition: service_healthy
        restart: true
      radarr:
        condition: service_healthy
        restart: true

  unpackerr:
    container_name: unpackerr
    # See more: https://unpackerr.zip/docs/install/compose
    image: golift/unpackerr
    restart: always
    env_file: ./env/arr.env
    volumes:
      - unpackerr:/config
      - media:/media
      - downloads:/downloads
    depends_on:
      sonarr:
        condition: service_healthy
        restart: true
      radarr:
        condition: service_healthy
        restart: true

networks:
  default:
    name: media_network
    driver: bridge
    attachable: true

volumes:
  downloads:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${DOWNLOADS_VOLUME}"

  media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${MEDIA_VOLUME}"

  sonarr: # Sonarr app data.
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${DOCKER_VOLUME}/sonarr"

  radarr: # Radarr app data.
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${DOCKER_VOLUME}/radarr"

  prowlarr: # Prowlarr app data.
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${DOCKER_VOLUME}/prowlarr"

  unpackerr: # unPackerr app data.
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${DOCKER_VOLUME}/unpackerr"
