---

services:
  overseerr:
    # See more: https://docs.overseerr.dev/getting-started/installation
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: always
    env_file: ./env/overseerr.env
    volumes:
      - overseerr:/app/config
    healthcheck:
      test: wget http://localhost:5055/api/v1/status -qO /dev/null || exit 1
      interval: 10s
      timeout: 3s
      start_period: 60s
    depends_on:
      caddy:
        condition: service_healthy
        restart: true
      plex:
        condition: service_healthy
        restart: true

  plex:
    # See more: https://docs.linuxserver.io/images/docker-plex/
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: always
    env_file: ./env/plex.env
    volumes:
      - media:/media
      - ${PLEX_PATH}/config:/config
      - ${PLEX_PATH}/data:/data
      - ${PLEX_PATH}/transcode:/transcode
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:32400/identity || curl -fsS http://$(hostname -i):32400/identity || exit 1"]
      interval: 10s
      timeout: 3s
      start_period: 60s
    depends_on:
      caddy:
        condition: service_healthy
        restart: true

networks:
  default:
    name: media_network
    driver: bridge
    attachable: true

volumes:
  media: # Media library
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${MEDIA_VOLUME}"

  overseerr: # Overseerr app data.
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},rw,tcp,nolock,hard,wsize=65536,rsize=65536"
      device: ":${DOCKER_VOLUME}/overseerr"
